language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - virtualenv ./env  --system-site-packages
  - source ./env/bin/activate
  - sudo pip3 install -r requirements.txt
  - sudo python3 setup.py install
# command to run tests
script: 
  - nosetests

