language: python
python:
- "3.4"
# command to install dependencies
install:
  - sudo apt-get update
  - sudo apt-get install python3-apt
  - pip install -r requirements.txt
  - pip install nose
  - python setup.py install
  - ee --help
script: nosetests
