language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
 - sudo apt-get install python-pip git
 - sudo apt-get install python-dev
 - sudo apt-get install gcc
 - sudo apt-get install python-dateutil python-docutils python- feedparser python-gdata python-jinja2 python-ldap python-libxslt1 python-lxml python-mako python-mock python-openid python-psycopg2 python-psutil python-pybabel python-pychart python-pydot python-pyparsing python-reportlab python-simplejson python-tz python-unittest2 python-vatnumber python-vobject python-webdav python-werkzeug python-xlwt python-yaml python-zsi
 - pip3 install virtualenv
 - source ~/virtualenv/python3.4/bin/activate --system-site-packages
 - pip install virtualenv
 - pip install -r requirements.txt
 - python setup.py develop
# command to run tests
script: 
  - nosetests

