language: python
python:
  - "3.4"
# command to install dependencies
install:
  - sudo apt-get install python3-pip git
  - python3 --version
  - sudo python3 setup.install
  - ee --help
  
# command to run tests
script: nosetests
