language: python
python:
- "3.4"
# command to install dependencies
install:
  - sudo apt-get update
  - sudo apt-get install python3-apt
  - which pip3
  - which python3
  - pip --version
  - python --version
script: nosetests
